blog/urls.py
from django.urls import include ,path
from .views import  PostDetailView , PostCreateView ,PostUpdateView ,PostDeleteView
from . import views

urlpatterns = [
    path('', views.about , name='blog-about'),
    path('home/', views.home , name='blog-home'),
    path('post/view/<int:pk>/',PostDetailView.as_view(),name='post-detail'),   
    path('post/new/',PostCreateView.as_view(),name='post-create'),
    path('post/update/<int:pk>/',PostUpdateView.as_view(),name='post-update'),   
    path('post/delete/<int:pk>/',PostDeleteView.as_view(),name='post-delete'),   
]

workpick/urls.py
from django.urls import path, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/',user_views.register,name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('profile/' ,user_views.profile ,name='profile'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('',include('blog.urls')),
    path('password-reset/',
    auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),name='password_reset'),
     path('password-reset-done/',
    auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),name='password_reset_done'),
      path('password-reset-confirm/<uidb64>/<token>/',
    auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),name='password_reset_confirm'),
     path('password-reset-complete/',
    auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),name='password_reset_complete'),
 
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.CharField(max_length=100)
    date_posted = models.DateField(default=timezone.now)
    author = models.ForeignKey(User, on_delete = models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.pk})
        

users/models.py
from django.db import models
from django.contrib.auth.models import User 
from PIL import Image
from languages.fields import LanguageField
from django_countries.fields import CountryField
import datetime
from phone_field import PhoneField
class Language(models.Model): 
    language = LanguageField()
   
    def __str__(self):
        return self.language
class Disability (models.Model):
    disability = models.CharField(max_length=30)
  
    def __str__(self):
        return self.disability
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    firstname = models.CharField(max_length=30, default='nombre')
    lastname = models.CharField(max_length=30, default='apellido')
    phone = PhoneField(blank=True, help_text='Numero de Celular')
    country = CountryField(blank_label='(select country)')
    bornDate = models.DateField('Fecha de nacimiento',blank=False,default=datetime.date.today)
    image  = models.ImageField(default='default.png',upload_to='profile_pics')
    disability = models.ManyToManyField(Disability)
    language = models.ManyToManyField(Language)
  
    def __str__(self):
        return f'{self.user.username} Profile'




    

users/forms.py
from django import forms 
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import views as auth_views
from .models import Profile , Language , Disability

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model  = User
        fields = ['username','email','password1','password2']
        
class UserUpdateForm(forms.ModelForm):
    
    email = forms.EmailField()
    class Meta:
            model = User
            fields = ['username','email']

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
            model = Profile
            fields  = ['firstname','lastname','phone','country','bornDate','image']
class ProfileLanguageForm(forms.ModelForm):
     class Meta:
            model = Language 
            fields = ['language']
class ProfileDisabilityForm(forms.ModelForm):
    class Meta: 
            model = Disability
            fields = ['disability']

blog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin ,UserPassesTestMixin
from django.views.generic import ListView, DetailView , CreateView ,UpdateView ,DeleteView
from .models import Post
from django.core.paginator import Paginator

def home(request):
    post_list = Post.objects.all()
    paginator = Paginator(post_list, 3) # Show 25 contacts per page
    page = request.GET.get('page')
    posts = paginator.get_page(page)
    return render(request, 'blog/home.html', {'posts': posts})

class PostDetailView(DetailView):
    model = Post 
    template_name = 'blog/post_detail.html'

class PostCreateView(LoginRequiredMixin,CreateView):
    model = Post
    fields = ['title','content']
    
    def form_valid(self,form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class PostUpdateView(LoginRequiredMixin,UpdateView ,UserPassesTestMixin):
    model = Post
    fields = ['title','content']
    
    def form_valid(self,form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False
class PostDeleteView(LoginRequiredMixin,DeleteView,UserPassesTestMixin):
    model = Post
    success_url = '/home'
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False 

def about(request):
    return render(request,'blog/about.html')

users/views.py
from django.shortcuts import render ,redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm, UserUpdateForm , ProfileUpdateForm ,ProfileLanguageForm ,ProfileDisabilityForm



def register(request):
	if request.method == 'POST':
		form = UserRegisterForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data.get('username')
			messages.success(request, f'Cuenta Creada para {username}!')
			return redirect('login')
	else:
			form = UserRegisterForm()

	return render(request,'users/register.html',{'form':form })

@login_required
def profile(request):
	if request.method == 'POST':               
		u_form = UserUpdateForm(request.POST,instance=request.user)
		p_form = ProfileUpdateForm(request.POST,request.FILES,instance=request.user.profile)

		if u_form.is_valid() and p_form.is_valid():
			u_form.save()
			p_form.save()
			messages.success(request,f'Tu perfil a sido actualizado!')
			return redirect('profile')
		else:
			messages.error(request,f'Lo sentimos, Ya existe un usuario con ese nombre')
			return redirect('profile')
	else:
		u_form = UserUpdateForm(instance=request.user)
		p_form = ProfileUpdateForm(instance=request.user.profile)
		d_form = ProfileDisabilityForm(instance=request.user)
		l_form = ProfileLanguageForm(instance=request.user.profile)

		context = {
		'u_form':u_form,
		'p_form':p_form,
		'd_form':d_form,
		'l_form':l_form,
		}

	return render(request , 'users/profile.html',context)

blog/templates/blog/about.html
{% extends "blog/base.html" %}
{% block content %}

<section class=".container-fluid">
<div class="row" style="background-color:blueviolet">
  <div class="col-md-4">
    <div class="jumbotron animated slideInLeft" style="background-color:white">
      <img src="./img/send.png">
      <h4>Facil de contacto</h4>
      <h6>Conectate con personas que comparten tus intereses</h6>
    </div>

  </div>

  <div class="col-md-8">
    <div class="jumbotron animated slideInRight" style="background-color:chocolate">
      <img src="">
      <h4>Facil de contacto</h4>
      <h6>Conectate con personas que comparten tus intereses</h6>
    </div>

  </div>
</div>


<div class="row" style="background-color:blueviolet">
  <div class="col-md-8">
    <div class="jumbotron animated slideInLeft" style="background-color:chocolate">
      <img src="">
      <h4>Facil de contacto</h4>
      <h6>Conectate con personas que comparten tus intereses</h6>
    </div>

  </div>
  <div class="col-md-4">
    <div class="jumbotron animated slideInRight" style="background-color:white">
      <img src="./img/star.png">
      <h4>Facil de contacto</h4>
      <h6>Conectate con personas que comparten tus intereses</h6>
    </div>

  </div>

</div>

<div class="row" style="background-color:blueviolet">
  <div class="col-md-3">
    <div class="jumbotron animated slideInLeft" style="background-color:white">
      <img src="./img/save.png">
      <h4>Facil de contacto</h4>
      <h6>Conectate con personas que comparten tus intereses</h6>
    </div>

  </div>
  <div class="col-md-9">
    <div class="jumbotron animated slideInRight" style="background-color:chocolate">
      <img src="">
      <h4>Facil de contacto</h4>
      <h6>Conectate con personas que comparten tus intereses</h6>
    </div>

  </div>
</div>






</section>
    

{% endblock content %}
 

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet" type ="text/css" href="{% static 'blog/css/animate.min.css' %}">
  <link rel="stylesheet" type ="text/css" href="{% static 'blog/css/custom.css' %}">
    <link rel="stylesheet" type ="text/css" href="{% static 'blog/css/jquery.inputlimiter.1.0.css' %}">
    <link rel="stylesheet" type="text/css" href=" {% static 'blog/css/jquery-ui.css' %}">
    <link rel="stylesheet" type="text/css" href=" {% static 'blog/css/jquery-ui.structure.css' %}">
    <link rel="stylesheet" type="text/css" href=" {% static 'blog/css/jquery-ui.theme.css' %}">
  
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
  <title>WorkPick</title>
</head>

<body>
  <div class="bg"></div>
  <header class="sticky-top">
  <nav class="navbar navbar-expand-md navbar-dark bg-primary">

    <div class="container"> 
    <a class="navbar-brand" href="{% url 'blog-about'%}" style="">
        <div class="row">
          <div class="col-md-12">
            <div class="row">
              <div class="col-md-11 ml-1" style="">
                <p class="mb-0">WorkPick</p>
              </div>
            </div>
          </div>
        </div>
      </a> <button class="navbar-toggler collapsed" type="button" data-toggle="collapse"
        data-target="#navbar16">
        <span class="sr-only"></span>
        <span class="icon-bar"> <i class ="fas fa-cog"></i></span>
        
      </button>
      <div class="collapse navbar-collapse" id="navbar16">
        <ul class="navbar-nav ml-auto"> 
        {% if user.is_authenticated %}
       
       
        <a class="nav-item nav-link" href="{% url 'profile' %}"> <img class="rounded-circle" src="{{user.profile.image.url}}" style="height:25px;
  width: 25px; margin-right:3px;">{{user.username}}</a>
        <a class="nav-item nav-link" href="{% url 'password_reset' %}">Seguridad<i class=""></i></a>
        <a class="nav-item nav-link" href="{% url 'logout' %}">salir <i class="fas fa-sign-out-alt"></i></a>
        {% else %}
        <a class="nav-item nav-link" href="{% url 'login' %}">Entrar <i class="fas fa-sign-in-alt"></i></a>
        <a class="nav-item nav-link" href="{% url 'register'%}">Registrar</a>
        {% endif %} 
        </ul> 
      </div> 
  </nav>
   {% if user.is_authenticated %}
  <div class="container">
     <div class="row" style="padding-top:5px; padding-bottom:5px;">
      <div class="col-2 d-flex justify-content-center"><a class="btn btn-light shadow-sm" href="{% url 'blog-home' %}" ><i class="fas fa-home"></i></a></div>
      <div class="col-2 d-flex justify-content-center"><a class="btn btn-light shadow-sm" href="{% url 'post-create' %}"><i class="fas fa-plus"></i></a></div>
      <div class="col-2 d-flex justify-content-center"><a class="btn btn-light shadow-sm" href=""><i class="fas fa-bell"></i></a></div>
      <div class="col-2 d-flex justify-content-center"><a class="btn btn-light shadow-sm" href=""><i class="fas fa-user"></i></a></div>
      <div class="col-2 d-flex justify-content-center"><a class="btn btn-light shadow-sm" href=""><i class="fas fa-trash"></i></a></div>
      <div class="col-2 d-flex justify-content-center"><a class="btn btn-light shadow-sm" href=""><i class="fas fa-envelope"></i></a></div>
    </div>
  </div>
     

	  {% endif %}
  
</header>

{% block content%}

{% endblock  %}
  
   <footer class="container">
    <p>WorkPick, Copyright &copy; 2019</p>
  </footer>
  <script type="text/javascript" src="{% static 'blog/js/jquery.js' %}">
</script>
<script type="text/javascript" src="{% static 'blog/js/bootstrap.min.js' %}">
</script>
<script type="text/javascript" src="{% static 'blog/js/popper.min.js' %}">
</script>
<script type="text/javascript" src="{% static 'blog/js/jquery.inputlimiter.1.3.1.min.js' %}">
</script>

<script type="text/javascript" src="{% static 'blog/js/jquery-ui.js' %}">
</script>
<script type="text/javascript" src="{% static 'blog/js/jquery.ae.image.resize.min.js' %}">
</script>

{% block extra_js %}

{% endblock extra_js %}
  
  
</body>

</html>

blog/templates/blog/home.html
{% extends "blog/base.html" %}
{% block content %}
<form>
  <div class="form-group">
    <div class="container">
      <div class="row">
        <div class="col-9">
          <input type="text" class="form-control" placeholder="Buscar" name="searchPost">
        </div>
        <div class="col-3">
          <button type="submit" class="btn btn-default btn-block"><i class="fa fa-search"></i></button>
        </div>
      </div>

    </div>
  </div>
</form>
{% for post in posts %}
<div class="card" style="width: 20rem;  border-radius: 0px; ">
  <div class="card-body">
    <h5 class="card-title">{{post.title}}</h5>
    <p class="card-text">
      el dia:{{post.date_posted|date:"F d ,Y"}}
    </p>
    <a href="{% url 'post-detail' post.id %}" class="btn btn-primary" style="border-radius: 0px; ">Ver detalles</a>
  </div>
</div>
{% endfor %}
<ul class="pagination">
  {% if posts.has_previous %}
  <li class="page-item"><a class="page-link" href="?page=1">&laquo; first</a></li>
  <li class="page-item"><a class="page-link" href="?page={{ posts.previous_page_number }}">previous</a></li>
  {% endif %}
  <span class="page-link">
    Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
  </span>
  {% if posts.has_next %}
  <li class="page-item"><a class="page-link" href="?page={{ posts.next_page_number }}">next</a></li>
  <li class="page-item"><a class="page-link" href="?page={{ posts.paginator.num_pages }}">last &raquo;</a></li>
  {% endif %}
</ul>
{% endblock content %}
{% block extra_js %}
{% endblock extra_js %}

blog/templates/blog/post_confirm_delete.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <form  method="POST" class="form-group jumbotron" style="margin-top:15px;">
          <div class="page-header">
            <h3 class=""> Eliminar Oferta </h3>
            <hr>
            </div>
            <div class="form-group">
            {% csrf_token %}
            {{ form|crispy }}
            <br>
            <button type="submit" class="btn btn-warning">Eliminar</button>
            <a href="{% url 'post-detail' object.id %}" class="badge badge-primary">Cancelar</a>
            </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}
{% block extra_js %}
<script>
$(document).ready(function() {        
    // The limiter will display the text in Spanish
    $('[name ="username"]').inputlimiter({
        limit: 15,
        remText: '%n caractere%s restantes.',
        limitText: 'Usuario limitado a %n caractere%s.'
    });
    $('[name ="email"]').inputlimiter({
        limit: 30,
        remText: '%n caractere%s restantes.',
        limitText: 'Correo electronico limitado a %n caractere%s.'
    });
      $('[name ="password1"]').inputlimiter({
        limit: 15,
        remText: '%n caractere%s restantes.',
        limitText: 'Contrasena limitado a %n caractere%s.'
    });
     $('[name ="password2"]').inputlimiter({
        limit: 15,
        remText: '%n caractere%s restantes.',
        limitText: 'Contrasena limitado a %n caractere%s.'
    });
    $('#hint_id_username').hide();
    $('#hint_id_password1').hide();
});
$('[name ="username"]').keypress(function (e) {
    var regex = new RegExp("^[a-zA-Z0-9]+$");
    var str = String.fromCharCode(!e.charCode ? e.which : e.charCode);
    if (regex.test(str)) {
        return true;
    }
    e.preventDefault();
     return false;
});
$('[name ="password1"]').click(function() {
    $('#hint_id_password1').fadeIn();
});
</script>
{% endblock extra_js %}

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}
{% block content %}
{% if object.author == user %}
<div class="container" style="padding-top:5px; padding-bottom:5px;">

        <div class="row">
                <a href="{% url 'post-update' object.id %}" class="btn-sm badge badge-success">Actualizar</a>
                <a href="{% url 'post-delete' object.id %}" class="btn-sm badge badge-danger">Eliminar</a>
        </div>
</div>


{% endif %}

<div id="tabs">
        <ul>
                <li><a href="#tabs-1">Resumen</a></li>
                <li><a href="#tabs-2">Equipo</a></li>
                <li><a href="#tabs-3">Fotos</a></li>
        </ul>
        <div id="tabs-1">
                <p><a href="#" class="badge badge-primary">{{object.author}}</a>
                        {{object.date_posted|date:"F d ,Y"}}
                </p>
                <a href="#" class="">{{ object.title }}</a>
                <p class="form-text text-muted">
                        {{ object.content }}
                </p>
        </div>
        <div id="tabs-2">
                <p></p>
        </div>
        <div id="tabs-3">
                <p></p>
                <p></p>
        </div>
</div>

{% endblock content %}
{% block extra_js %}
<script>
        $(function () {
                $("#tabs").tabs();
        });
</script>
{% endblock extra_js %}

blog/templates/blog/post_form.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <form  method="POST" class="form-group jumbotron" style="margin-top:15px;">
          <div class="page-header">
            <h3 class=""> Publica una oferta de empleo</h3>
            <hr>
            </div>
            <div class="form-group">
            {% csrf_token %}
            {{ form|crispy }}
            <br>
            <button type="submit" class="btn btn-primary">Publicar</button>
            </div>

            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}
{% block extra_js %}
<script>

</script>
{% endblock extra_js %}

users/templates/users/login.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<div class="hero-image">
	<div class="container">
		<div class="row">
			<div class="col-md-6">
				<form id="form"  method="POST" class="form-group jumbotron">
					<div class="page-header">
						<h3 class="animated flash"> Inicia sesion</h3>
						<hr>
					 <div class="row">
					 <div class="col">
					 {% if messages %}
					 	{% for message in messages %}
					 	<div class=" alert alert-{{ message.tags }}">
							  {{ message }}
						 </div>
						
					 	{% endfor %}
					 {% endif %}
					 </div>
					 </div>
						</div>
						<div class="form-group">
						<br>
						<form method="POST">
						{% csrf_token %}
						{{ form|crispy }}
						 <button type="submit" class="btn btn-primary">Iniciar Sesion</button>
						</form>   
						<small class="text-muted ml-2">
								
								  <a class="" href=" {% url 'password_reset' %}">Restablecer contrasena</a> 
							</small>
						</div>
							
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock content %}
{% block extra_js %}
<script>
$('[name ="username"]').keypress(function (e) {
    var regex = new RegExp("^[a-zA-Z0-9]+$");
    var str = String.fromCharCode(!e.charCode ? e.which : e.charCode);
    if (regex.test(str)) {
        return true;
    }

    e.preventDefault();
    return false;
});
$(document).ready(function() {        
    $('[name ="username"]').inputlimiter({
        limit: 40,
        remText: '%n caractere%s restantes.',
        limitText: 'Usuario limitado a %n caractere%s.'
    });
    $('[name ="email"]').inputlimiter({
        limit: 30,
        remText: '%n caractere%s restantes.',
        limitText: 'Correo electronico limitado a %n caractere%s.'
    });
          
    $('#hint_id_username').hide();
    $('#hint_id_password1').hide();
});
</script>
{% endblock extra_js %}

users/templates/users/logout.html
{% extends "blog/base.html" %}
{% block content %}
<h2> has salido de workpick </h2>
<div class="border-top pt-3">
<small class="text-muted">
Ya tienes una cuenta?
<a class = "ml-2" href="{% url 'login' %}"> Entrar!</a>
</small>
{% endblock content %}

users/templates/users/password_reset_complete.html
    {% extends "blog/base.html" %}
    {% block content %}

        <div class="container">
            <div class="alert alert-primary" role="alert">
                <strong>Tu contrasena a sido cambiada </strong>
                </div>
        </div>
    {% endblock content %}

users/templates/users/password_reset_confirm.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
        <div class="container">
            <form method="POST">
            {% csrf_token %}
                <div class="form-group row">
                    <label for="inputName" class="col-sm-1-12 col-form-label"></label>
                    <div class="col-sm-1-12">
                        <input type="text" class="form-control" name="inputName" id="inputName" placeholder="">
                    </div>
                </div>
                <fieldset class="form-group row">
                  {{ form|crispy }}
                </fieldset>
                <div class="form-group row">
                    <div class="offset-sm-2 col-sm-10">
                        <button type="submit" class="btn btn-primary">Cambiar Contrasena</button>
                    </div>
                </div>
            </form>
        </div>
</div>

{% endblock content %}

users/templates/users/password_reset_done.html
{% extends "blog/base.html" %}
{% block content %}
    <h2> Has terminado la configuracion</h2>
        <div class="border-top pt-3">
            <small class="text-muted">
                Selecciona otra configuracion
                <a class = "ml-2" href="{% url 'blog-home' %}"> Regresar</a>
            </small>
        </div>
{% endblock content %}

users/templates/users/profile.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<style>
  body {
    background-color: #E9ECEF;
  }
</style>
<div class="container">
  <div class="jumbotron" style="padding-top:2%;%">

    <h5> Configuracion de perfil <strong>{{user.username}}</strong></h5>

    <hr class="my-2">
    <p>*Algunos de los siguientes datos son obligatorios</p>
    <div class="form-group">
      <div class="row">
        <div class="col-11 jumbotron" style="background-color:white;">
          <div class="row">
            <div class="col">
              <div class="row">
                <div class="col text-center">
                  <img class=" account-img" src="{{user.profile.image.url}}">
                </div>
              </div>
            </div>
            <div class="col">
              <div class="row">
                <div class="col">
                  {% if messages %}
                  {% for message in messages %}

                  <div class=" alert alert-{{ message.tags }}">
                    {{ message }}
                  </div>

                  {% endfor %}
                  {% endif %}
                </div>
              </div>
              <div class="row">
                <div class="col">
                  <form method="POST" onclick="var()" enctype="multipart/form-data">
                    {% csrf_token %}
                    <fieldset class="form-group">
                      {{ u_form|crispy }}
                      {{ p_form|crispy }}
                      <button class="btn btn-primary" id="image" type="button">
                        Subir foto
                      </button>
                    </fieldset>
                             <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Configuracion</button> <br>
                    <button class="btn btn-block btn-light" type="submit"> Guardar</button>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Agregar Lenguaje | Discapacidad </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
       <div class="modal-body">
        <form>
          <div class="form-group">
                 {{ d_form|crispy }}
                      {{ l_form|crispy }}
          </div>
           <button type="submit" class="btn btn-primary">Guardar</button>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
       
      </div>
    </div>
  </div>
</div>

{% endblock content %}
{% block extra_js %}
<script>
  $(document).ready(function () {
    $('[name ="username"]').inputlimiter({
      limit: 15,
      remText: '%n caractere%s restantes.',
      limitText: 'Usuario limitado a %n caractere%s.'
    });
    $('[name ="email"]').inputlimiter({
      limit: 30,
      remText: '%n caractere%s restantes.',
      limitText: 'Correo electronico limitado a %n caractere%s.'
    });

    $('#hint_id_username').hide();
    $('#hint_id_password1').hide();
    $(".account-img").aeImageResize({
      height: 200,
      width: 200
    });
    $('#id_image').hide();
  });
  $('[name ="username"]').keypress(function (e) {
    var regex = new RegExp("^[a-zA-Z0-9]+$");
    var str = String.fromCharCode(!e.charCode ? e.which : e.charCode);
    if (regex.test(str)) {
      return true;
    }
    e.preventDefault();
    return false;
  });
  $('[name ="password1"]').click(function () {
    $('#hint_id_password1').show();
  });

  $(function () {
    $('#id_bornDate').datepicker({
      changeMonth: true,
      changeYear: true,
      yearRange: "-80:+0",
    });
  });
  $("#image").click(function () {
    $("#id_image").click();
  });
</script>
{% endblock extra_js %}